### ISSUE TITLE
How to use???

### ISSUE THREAD

**Issue by GerhardKreuzer** [Anvell/MVVM-Sample#1]
Hi,
just found this nice sample.
Get it working after updating the packages and removing a 'Style' clause in TableOneView.

Ok and what now?

File/New and I can create a data file (.db). I entered some data in the property fields, but no button to 'Save' this data.

Please give some documentation for playing around. Thanks.

With best regards

Gerhard

**Comment by Anvell** [comment]
Hi Gerhard,

the property panel is data bound to currently selected row which can be created by using Ctrl+N shortcut. There are some basic actions defined in MainViewModel.cs which are wired to menu and/or shortcuts in MainView.xaml.

Input from specific field on the property panel will be reflected in DataGrid once you leave that field as per UpdateSourceTrigger=LostFocus data binding rule. 

Best regards,
Denis
